"""change constraints for history table

Revision ID: d48afcccaf42
Revises: 312269bcdf13
Create Date: 2024-01-20 16:35:39.893020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48afcccaf42'
down_revision: Union[str, None] = '312269bcdf13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('history', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('history', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('history', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
